### ISSUE TITLE
La validación de URL de video en el formulario de propuesta es incorrecta

### ISSUE THREAD

**Issue by nicopaez** [nicopaez/opencall#10]
Actualmente hay algunas URL válidas que las marca como no valids.

Ejemplo: https://www.youtube.com/watch?v=lVPFu5aRo3Y&feature=youtu.be

Creo que lo más sano será sacar la validación y hace que simplemente se fije que no está en blanco.

**Comment by fdibartolo** [comment]
Actualicé la regular expression. Pendiente tener una suite de frontend tests, mas allá de los que hay de end-to-end.
