### ISSUE TITLE
Automatizar provisionamiento de instancia en heroku

### ISSUE THREAD

**Issue by fdibartolo** [nicopaez/opencall#102]
Entre otras cosas: 
- configurar terraform
- crear tareas rake para provisionar/destruir
- readme específico

**Comment by nicopaez** [comment]
Esto seria para el caso de querer correr fuera de Heroku, correcto?

**Comment by fdibartolo** [comment]
No, esto es específicamente para generar instancias en heroku (`rake open_call:heroku:create`).
Aun así, por otro lado tenemos `rake open_call:vm:setup`, que te genera una vm en virtualbox, aunque con unos pequeños cambios se puede hacer que la genere en aws; cosa que si se podría usar para correr fuera de heroku.
