### ISSUE TITLE
Optimizar indexado y búsqueda de propuestas

### ISSUE THREAD

**Issue by federicojsequeira** [nicopaez/opencall#116]
Configurar el mapping de las propuestas de modo que:

1- En el proceso de indexación solo se analicen los campos sensibles de búsqueda (se podría evitar el analisis sobre el campo _video link_, _avatar url_, cuáles mas?)

NOTA: aunque no se analice un campo será indexado de todas formas.

2- Búsquedas con palabras parciales devuelvan propuestas que contienen esas palabras en algunos de los campos. Por ej: 
**Sesion 1**
- titulo:  "Sesion numero 1"
- autor: "Federico"

Si buscamos "ses" o "nume" tendremos como resultado la Sesion 1 porque matchea parcialmente con el campo _titulo_. De la misma forma si buscamos "fede" matcheará por el campo _autor_

A DEFINIR: que campos usarían esta configuración? (título, autor, descripcion, etc)

**Comment by fdibartolo** [comment]
@federicojsequeira tenés en mente cómo implementarlo?
Sin ánimo de comprometerte, decime si está en tus planes submitir un PR.
Gracias!!

**Comment by federicojsequeira** [comment]
Si, tengo algo en un branch, tengo que revisarlo. Mando un PR en cuanto lo tenga.

**Comment by fdibartolo** [comment]
:+1::+1::+1:

**Comment by federicojsequeira** [comment]
## Enhancement final
Configurar el mapping de las propuestas de modo que:
1- En el proceso de indexación solo se analizan los campos sensibles de búsqueda (se evita el análisis sobre el campo video link y avatar url)

2- Búsquedas de mínimo 3 caracteres devuelven propuestas que contienen esos caracteres en algunos de los campos título o autor. Por ej:

- Sesión  1
titulo: "Sesion numero 1"
autor: "Federico"

Si buscamos "ses" o "nume" tendremos como resultado la Sesion 1 porque matchea parcialmente con el campo título. De la misma forma si buscamos "fede" matcheará por el campo autor.

**Comment by fdibartolo** [comment]
Gracias @federicojsequeira!
Ahí acepté el PR, y se autodeployó a staging, pero no veo que esté funcionando. Lo pullee local y tampoco, tendrá que ver con la versión de ES? 
En fin, le pegamos una mirada, pero desde ya me gustó el refactor en un concern 👍

**Comment by federicojsequeira** [comment]
👍 mi versión local de ES es 2.3.3. Sabés que versión hay en stage? Así la pruebo en local.
Podés pasarme la url de open call stage? Gracias!

**Comment by federicojsequeira** [comment]
Olvidé mencionar que habría que regenerar el índice y volver a indexar el contenido para que tome las nuevas reglas de analísis :)

**Comment by fdibartolo** [comment]
_Olvidé mencionar que habría que regenerar el índice y volver a indexar el contenido para que tome las nuevas reglas de analísis :)_ **BOOM!** 😄 👍 
En breve lo mergeo a prod, gracias!!

**Comment by federicojsequeira** [comment]
😄 👍 closed!
