### ISSUE TITLE
Como revisiones quiero que la evaluación de propuestas tenga tan solo 4 posibles valores

### ISSUE THREAD

**Issue by nicopaez** [nicopaez/opencall#29]
Aceptación fuerte
Aceptación débil
Rechazo débil
Rechazo fuerte

**Comment by fdibartolo** [comment]
Esto me hace un poco de ruido, recuerdo las primera charlas que queríamos simplificar el proceso, y por ende agregar un puntaje a la sesión, para luego hacer un promedio entre las revisiones que la misma tenga. Justamente estos 4 valores no queríamos acarrearlos de la plataforma anterior.
Por otro lado, pero esto ya es mas técnico, el cambio no es trivial; el score de una revisión se usa en unos cuantos lugares :S.
Buscamos un hueco y lo hablamos.

**Comment by nicopaez** [comment]
uuuuhhh, recién ahora veo este comentario.
No se si queríamos simplificar el proceso, queríamos mejorarlo y creo que eso hicimos. La forma en que lo implementé sigue permitiendo promediar, pues los 4 valores se mapean a -2, -1, 1 y 2, lo cual incluso refleja el  hecho de evaluación negativa.
Me llevo un más de lo que esperaba, pero ya está. Las modificaciones estan en el branch evaluations.
