### ISSUE TITLE
Como chair quiero mandar mensajes masivos a los usuarios

### ISSUE THREAD

**Issue by fdibartolo** [nicopaez/opencall#48]

**Comment by fdibartolo** [comment]
No cerremos este issue hasta agregar los specs que faltan de notifications_controller, mailer, user

**Comment by nicopaez** [comment]
para mi no tiene sentido agregar tests al notification_controller pues
tiene tan solo 1 linea de código

**Comment by fdibartolo** [comment]
No molesta, los agregué ya que también puse una validación sobre los params.
