### ISSUE TITLE
Soporte para el proceso de evaluación

### ISSUE THREAD

**Issue by nicopaez** [nicopaez/opencall#57]

**Comment by fdibartolo** [comment]
Comenzaré a trabajar sobre esto

**Comment by nicopaez** [comment]
Joya, coordinemos a ver pode,os meter algo de pairing

On Tuesday, June 16, 2015, Fernando Di Bartolo notifications@github.com
wrote:

> Comenzaré a trabajar sobre esto
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicopaez/opencall/issues/57#issuecomment-112599832.

## 

Saludos!
NicoPaez http://nicopaez.wordpress.com/

**Comment by nicopaez** [comment]
Agrego la info que mandé por mail y algo más que surgio hoy de una charla con Pablo y Hiro.

Primero que vamos a necesitar es una tabla donde se pueda ver:

título de sesion | autor | temática | cantidad de evaluaciones | acciones

Para mi esta tabla debería ver al estilo excel, o sea letra chica y uniforme en todas las columnas y con las posibilidad de ordenar por las distintas columnas.
En la columna de acciones tiene que tener un boton para "Evaluar".

La evaluación seria similar a lo que ahora tenemos como "Formal review" que de hecho deberíamos ajustarlo pues no sería review (eso es lo que estamos haciendo ahora) sino que sería "evaluation". Esa evaluación tener los siguiente datos:
- Pair: el par con quien se realizó la evaluación
- Nivel de confianza del evaluador: alto , medio, bajo
- Public comments: que podrian llegarle al autor (digo podria pues dependerá de lo que decida el chair).
- Private comments: esto no lo veria el autor, pero si los otros revisores
- Evaluation: strong accept | weak accept | weak reject | strong reject

Con esto tenemos lista la etapa de evaluación. Tengamos presente que el foco aquí es poder evaluar. Luego por otro lado (en la siguiente etapa) vendrá la selección donde los chairs verán las evaluación y junto con otra info seleccionarán las sesiones y recién ahí notificarán a los autores.

**Comment by fdibartolo** [comment]
@nicopaez pegale una mirada al reporte en staging. Falta actualizar el form de evaluación aun.
Se accede desde Menu > Reviews status.
